services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root.1234
      MYSQL_DATABASE: modulo9
      MYSQL_USER: userdb
      MYSQL_PASSWORD: User.1234
    ports:
      - "3306:3306"
    volumes:
      - ./midatos:/var/lib/mysql

  poke-api:
    build: ./pokemonProyecto
    container_name: poke-api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/modulo9
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root.1234
    networks:
      - springboot-network
    ports:
      - "8081:8080"

volumes:
  mysql_data:

networks:
  springboot-network: